-- USERS
INSERT INTO INF_USER(ID, ATIVO, PASSWORD, USERNAME )
VALUES(1, 1, '$2a$10$vW/icz3McCXG59PyL0OVK.M9dNYsZ2P9U.noou1hJW4eI6qFY2NVO', 'admin');
INSERT INTO INF_USER(ID, ATIVO, PASSWORD, USERNAME )
VALUES(2, 0, '$2a$10$vW/icz3McCXG59PyL0OVK.M9dNYsZ2P9U.noou1hJW4eI6qFY2NVO', 'usertest');

-- ROLES
INSERT INTO INF_ROLE(ID, NM_ROLE)
VALUES(1, 'ROLE_ADMIN');
INSERT INTO INF_ROLE(ID, NM_ROLE)
VALUES(2, 'ROLE_USER');

-- USER ROLES

INSERT INTO INF_USER_ROLE (USER_ID, ROLE_ID)
VALUES(1,1);
INSERT INTO INF_USER_ROLE (USER_ID, ROLE_ID)
VALUES(2,2);