-- USERS
INSERT INTO INF_USER(ID, ATIVO, PASSWORD, USERNAME )
VALUES(1, 1, '$2a$10$vW/icz3McCXG59PyL0OVK.M9dNYsZ2P9U.noou1hJW4eI6qFY2NVO', 'admin');
INSERT INTO INF_USER(ID, ATIVO, PASSWORD, USERNAME )
VALUES(2, 0, '$2a$10$vW/icz3McCXG59PyL0OVK.M9dNYsZ2P9U.noou1hJW4eI6qFY2NVO', 'usertest');

-- ROLES
INSERT INTO INF_ROLE(ID, NM_ROLE)
VALUES(1, 'ROLE_ADMIN');
INSERT INTO INF_ROLE(ID, NM_ROLE)
VALUES(2, 'ROLE_USER');

-- USER ROLES

INSERT INTO INF_USER_ROLE (USER_ID, ROLE_ID)
VALUES(1,1);
INSERT INTO INF_USER_ROLE (USER_ID, ROLE_ID)
VALUES(2,2);

-- ADDRESS

INSERT INTO INF_ADDRESS(ID, NM_BAIRRO, NM_LOCALIDADE, NM_LOGRADOURO, NM_UF, NU_CEP)
VALUES(1, 'Centro', 'Rio de Janeiro', 'Avenida Presidente Vargas', 'RJ', '20071004');

-- PESSOA
INSERT INTO INF_PESSOA(ID, NU_CPF, NM_PESSOA, ADDRESS_ID)
VALUES(1, '24400234566', 'Maria da Silva', 1);

INSERT INTO INF_PESSOA(ID, NU_CPF, NM_PESSOA, ADDRESS_ID)
VALUES(2, '18135824009', 'João da Silva', 1);

-- BANCO

INSERT INTO INF_BANCO(ID, CD_BANCO, NM_BANCO)
VALUES(1, '001', 'Banco 1');
INSERT INTO INF_BANCO(ID, CD_BANCO, NM_BANCO)
VALUES(2, '002', 'Banco 2');

-- PESSOA_BANCON

INSERT INTO INF_PESSOA_CONTA_CORRENTE (ID, NU_AGENCIA, NU_CONTA_CORRENTE, BANCO_ID, PESSOA_ID)
VALUES(1, '0123', '123456789', 1, 1);